version = "Two"
edition = "2018"
unstable_features = true
error_on_line_overflow = true
error_on_unformatted = true
max_width = 110
comment_width = 100
reorder_impl_items = true
use_field_init_shorthand = true
overflow_delimited_expr = true
struct_field_align_threshold = 20
merge_imports = true
condense_wildcard_suffixes = true
indent_style = "Visual"
imports_layout = "Vertical"
