name: Continuous integration

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
        experimental: [false]
        cargo_flags: [--all-features]
        include:
          # Stop breakages in nightly to fail the workflow
          - rust: nightly
            experimental: true
            cargo_flags: --all-features
          # MSRV
          - rust: 1.65.0
            experimental: false
            cargo_flags: ""
          - rust: 1.81.0
            experimental: false
            cargo_flags: --all-features

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.cargo_flags }}

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.cargo_flags }}
