name: Clippy check

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
  merge_group:

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          # Note: some codegen tools actually format the code, so add rustfmt
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings -D clippy::all
